/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.clients;

import java.util.*;

public class App {
    public static void main(String[] args) {
        /*
         * Implementation below just to showcase the functionality
         *
         */
        ClientService clientService = new ClientService(
                2,
                1,
                2
        );
        List<ClientInfo> clients = ClientInfo.getTestClients();
        List<PotentialDuplicate> potentialDuplicates = clientService.searchPotentialDuplicates(clients);
        potentialDuplicates.forEach(System.out::println);
    }
}
